### ISSUE TITLE
useRandomNumber does not work as expected.

### ISSUE THREAD

**Issue by imp-dance** [btahir/uselesshooks#1]
Hi. Wonderful package. I've noticed that `useRandomNumber` does not in fact return a new random number on every render, since the useEffect does not have any dependencies it will only run once when the component that uses the hook mounts.

A simple solution would be this refactor:

```typescript
function useRandomNumber() {
  return Math.round(Math.random() * 100)
}

export default useRandomNumber
```

You could always also add a min/max to the hook:

```typescript
function useRandomNumber(min = 0, max = 100) {
  return Math.random() * (max - min) + min;
}

export default useRandomNumber
```

But I think adding this feature would make this package more useful, so maybe don't do that.

**Comment by imp-dance** [comment]
I've realised this fix will make the package more useful, so I've decided to close the issue.

**Comment by btahir** [comment]
Agreed - this is a bit too useful. 😃
